# This is a basic workflow to help you get started with Actions

name: Mod Update

# Controls when the action will run. 
on:
  # Run every hour, on the hour 
  schedule:
    - cron: "0 * * * *" 

  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    name: Page Generation

    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # If this is running under a pull request, it will also pull in those changes
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup Python
      - name: Python installation
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.3

      # Update pip and then install dependencies
      - name: Install dependencies
        working-directory: ./scripts
        run: |
          python -m pip install --upgrade pip
          pip install -r "requirements.txt"
  
      # Mod documentation is generated "softly" when the task has been scheduled
      # If mod documentation is faulty, it'll silently fail and not update the page of the given mod

      # Run generation script
      - name: Generate hard mod documentation
        if: ${{ github.event_name == 'pull_request' }}
        working-directory: ./scripts
        run: |
          python "./GenerateModDocs.py" --hard

      - name: Generate soft mod documentation
        if: ${{ github.event_name != 'pull_request' }}
        working-directory: ./scripts
        run: |
          python "./GenerateModDocs.py"

      # Deploy the site to the gh-pages branch **ONLY** if this is not a pull request
      # You can't actually run the workflow from master and then change files in master because Github Page's automatic page building runs BEFORE this workflow :/
      - name: Deploy website to gh-pages branch
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          enable_jekyll: true